server:
  port: 8006
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: nihil-test-auth-server
  profiles:
    include: auth
  datasource: # 配置数据库
    url: jdbc:mysql://localhost:3306/nihil_auth?serverTimezone=UTC&useAffectedRows=true
    username: user
    password: user123456
